# Generated by Django 2.1.2 on 2018-10-06 05:36

from django.db import migrations, models
import webclient.models


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0003_auto_20181006_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='media_file',
            field=models.FileField(default='', upload_to='webclient.FileModel/bytes/filename/mimetype'),
        ),
    ]
