# Generated by Django 2.1.2 on 2018-10-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0006_folder_folder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OFile',
        ),
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
    ]
