# Generated by Django 2.1.2 on 2018-10-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0007_auto_20181017_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='media_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
