# Generated by Django 2.1.3 on 2018-11-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0009_auto_20181023_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='md5sum',
            field=models.CharField(default='', max_length=250),
        ),
    ]
