# Generated by Django 2.1.3 on 2018-11-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0010_file_md5sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='var',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='folder',
            name='var',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='file',
            name='md5sum',
            field=models.CharField(default='0', max_length=250),
        ),
    ]
